spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: exchangerDB
      authentication-database: admin
      username: admin
      password: admin
  application:
    name: easy-exchanger
