spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: exchangerDB
      authentication-database: admin
      username: admin
      password: admin
  application:
    name: easy-exchanger

  config:
    import: optional:file:.env[.properties]


easy-exchanger:
  api-url: "https://v6.exchangerate-api.com"
  api-key: ${EXCHANGER_API_KEY:default-key}
